//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sh_SearchJobExpression
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_sh_SearchJobExpression()
        {
            this.tbl_jb_Search = new HashSet<tbl_jb_Search>();
            this.tbl_sh_SearchJobTerm = new HashSet<tbl_sh_SearchJobTerm>();
        }
    
        public long SearchJobExpressionId { get; set; }
        public Nullable<long> JobId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string SearchJobExpression { get; set; }
        public string ResultQuery { get; set; }
        public bool IsTermQueuingCompleted { get; set; }
        public string MergeOperator { get; set; }
        public Nullable<System.DateTime> MergedStartedOn { get; set; }
        public Nullable<System.DateTime> MergeCompletedOn { get; set; }
        public Nullable<long> MergeAndDumpResultStatus { get; set; }
        public Nullable<long> MergedByJobSearchId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_jb_Search> tbl_jb_Search { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sh_SearchJobTerm> tbl_sh_SearchJobTerm { get; set; }
    }
}
