//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ig_TimeoutJobAssociation
    {
        public long TimeOutLogId { get; set; }
        public long Jobid { get; set; }
    
        public virtual tbl_ig_FileTypeTimeoutLog tbl_ig_FileTypeTimeoutLog { get; set; }
    }
}
