//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VAR_ReviewBatchStatistics
    {
        public long StatisticsLogId { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<long> ReviewSetId { get; set; }
        public Nullable<long> BatchId { get; set; }
        public Nullable<decimal> BatchRichness { get; set; }
        public Nullable<decimal> CumulativeReviewRelevance { get; set; }
        public Nullable<System.DateTime> CommitedOn { get; set; }
        public Nullable<long> CommitedBy { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> SeedBatchRichness { get; set; }
        public Nullable<decimal> ControlSetRelevancy { get; set; }
        public Nullable<long> ProjectedRelevantDocCount { get; set; }
        public Nullable<long> TargetedRelevantDocCount { get; set; }
        public Nullable<long> CurrentRelevantDocCount { get; set; }
    }
}
