//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sh_SearchJobTerm
    {
        public long SearchJobTermId { get; set; }
        public Nullable<long> JobId { get; set; }
        public Nullable<long> SearchJobExpressionId { get; set; }
        public string SearchJobTerm { get; set; }
        public string Base64String { get; set; }
        public Nullable<bool> IsDTTerm { get; set; }
        public Nullable<bool> IsDynamicSearch { get; set; }
        public string ResultTable { get; set; }
    
        public virtual tbl_sh_SearchJobExpression tbl_sh_SearchJobExpression { get; set; }
    }
}
