//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ds_ProjectJobInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ds_ProjectJobInfo()
        {
            this.tbl_ig_PasswordReprocessLog = new HashSet<tbl_ig_PasswordReprocessLog>();
            this.tbl_ex_IndexStatusLog = new HashSet<tbl_ex_IndexStatusLog>();
            this.tbl_jb_GenericJobDetail = new HashSet<tbl_jb_GenericJobDetail>();
            this.tbl_jb_NDDJob = new HashSet<tbl_jb_NDDJob>();
            this.tbl_jb_OcrRedactedTiff = new HashSet<tbl_jb_OcrRedactedTiff>();
            this.tbl_jb_RTFJob = new HashSet<tbl_jb_RTFJob>();
            this.tbl_jb_SkippedJobFiles = new HashSet<tbl_jb_SkippedJobFiles>();
            this.tbl_jb_TiffPreQC = new HashSet<tbl_jb_TiffPreQC>();
            this.tbl_VAR_CG_shadow = new HashSet<tbl_VAR_CG_shadow>();
            this.tbl_VAR_JobInitiatedStatus = new HashSet<tbl_VAR_JobInitiatedStatus>();
            this.tbl_VAR_Prediction_shadow = new HashSet<tbl_VAR_Prediction_shadow>();
            this.tbl_VAR_TF_shadow = new HashSet<tbl_VAR_TF_shadow>();
        }
    
        public long JobId { get; set; }
        public string Name { get; set; }
        public long Status { get; set; }
        public bool IsQueuingCompleted { get; set; }
        public System.DateTime QueuedOn { get; set; }
        public Nullable<System.DateTime> Startedon { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public int QueuedBy { get; set; }
        public string BulkProcessingInstanceId { get; set; }
        public int BulkProcessingStatus { get; set; }
        public string OtherSettings { get; set; }
        public string DisplayRemarks { get; set; }
        public Nullable<long> ProjectJobGroupId { get; set; }
        public string PostProcessingStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ig_PasswordReprocessLog> tbl_ig_PasswordReprocessLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ex_IndexStatusLog> tbl_ex_IndexStatusLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_jb_GenericJobDetail> tbl_jb_GenericJobDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_jb_NDDJob> tbl_jb_NDDJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_jb_OcrRedactedTiff> tbl_jb_OcrRedactedTiff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_jb_RTFJob> tbl_jb_RTFJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_jb_SkippedJobFiles> tbl_jb_SkippedJobFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_jb_TiffPreQC> tbl_jb_TiffPreQC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VAR_CG_shadow> tbl_VAR_CG_shadow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VAR_JobInitiatedStatus> tbl_VAR_JobInitiatedStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VAR_Prediction_shadow> tbl_VAR_Prediction_shadow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VAR_TF_shadow> tbl_VAR_TF_shadow { get; set; }
    }
}
