//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jb_PromoteWorkProduct
    {
        public long JobId { get; set; }
        public long SourceFileId { get; set; }
        public int Status { get; set; }
        public string ProcessingInstanceId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> ReTryCount { get; set; }
        public int PromoteTagStatus { get; set; }
        public int PromoteFolderStatus { get; set; }
        public int PromoteCustomFieldStatus { get; set; }
        public int PromoteRedactionStatus { get; set; }
    }
}
