//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lg_GenericLog
    {
        public long LogId { get; set; }
        public string Application { get; set; }
        public string AppAssemblyVersion { get; set; }
        public string AppFileVersion { get; set; }
        public string AppHostMachine { get; set; }
        public string Module { get; set; }
        public Nullable<long> FileId { get; set; }
        public string SelectedMedia { get; set; }
        public string LogType { get; set; }
        public string LogMessage { get; set; }
        public string LogRemark { get; set; }
        public string LogDetail { get; set; }
        public string Data1 { get; set; }
        public string Data2 { get; set; }
        public string Data3 { get; set; }
        public string Data4 { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> JobId { get; set; }
        public string ProcessingInstanceId { get; set; }
        public Nullable<bool> IsStateError { get; set; }
        public string StateErrorType { get; set; }
    }
}
