//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jb_EmailNotification
    {
        public long EmailNotificationID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public Nullable<System.DateTime> EmailQueueDate { get; set; }
        public Nullable<System.DateTime> EmailSentDate { get; set; }
        public Nullable<int> RetryAttemptCount { get; set; }
        public long ProjectId { get; set; }
        public Nullable<bool> IsManualNotification { get; set; }
        public Nullable<bool> ReadyToSend { get; set; }
        public short Status { get; set; }
        public long ParentNotificationID { get; set; }
        public bool IncludeAttachmentInMail { get; set; }
        public Nullable<long> SettingId { get; set; }
        public Nullable<long> ClientId { get; set; }
    }
}
