//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pj_upgradeLog
    {
        public long LogId { get; set; }
        public string Version { get; set; }
        public string Patch { get; set; }
        public System.DateTime UpgradeStartDateTime { get; set; }
        public Nullable<System.DateTime> UpgradeEndDateTime { get; set; }
        public int Status { get; set; }
        public string Remarks { get; set; }
    }
}
