//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_TagHistory
    {
        public long TagHistoryID { get; set; }
        public long BatchID { get; set; }
        public long Tagid { get; set; }
        public bool DirectHit { get; set; }
        public long Custodianid { get; set; }
        public long Mediaid { get; set; }
        public long Fileid { get; set; }
    
        public virtual tbl_ex_tag tbl_ex_tag { get; set; }
        public virtual tbl_Ex_TagActionLog tbl_Ex_TagActionLog { get; set; }
    }
}
