//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VAR_CategoryInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_VAR_CategoryInfo()
        {
            this.tbl_VAR_TrainingItems = new HashSet<tbl_VAR_TrainingItems>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDesc { get; set; }
        public Nullable<long> TrainingTagID { get; set; }
        public Nullable<long> PredictionTagID { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<bool> IsPrimaryCategory { get; set; }
    
        public virtual tbl_ex_tag tbl_ex_tag { get; set; }
        public virtual tbl_ex_tag tbl_ex_tag1 { get; set; }
        public virtual tbl_VAR_ProfileInfo tbl_VAR_ProfileInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VAR_TrainingItems> tbl_VAR_TrainingItems { get; set; }
    }
}
