//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ig_ArchiveAsEdocs
    {
        public long ArchiveAsEdocFileId { get; set; }
        public long CustodianId { get; set; }
        public long MediaId { get; set; }
        public long FileId { get; set; }
        public string FileName { get; set; }
        public string AbsoluteFilePath { get; set; }
        public string Extension { get; set; }
        public string FileType { get; set; }
    }
}
