//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VAR_JobInitiatedStatus
    {
        public long Id { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<long> JobId { get; set; }
        public Nullable<bool> IsJobInitiated { get; set; }
    
        public virtual tbl_ds_ProjectJobInfo tbl_ds_ProjectJobInfo { get; set; }
        public virtual tbl_VAR_ProfileInfo tbl_VAR_ProfileInfo { get; set; }
    }
}
