//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ann_RedactionObjects
    {
        public int ObjectId { get; set; }
        public int RedactionType { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public string ObjectName { get; set; }
        public string ForeColor { get; set; }
        public string BackColor { get; set; }
        public string Caption { get; set; }
        public Nullable<decimal> FontSize { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    }
}
