//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pj_HTMLConversionSettings
    {
        public long HTMLConversionSettingId { get; set; }
        public bool ShowHiddenRowColumnSheet { get; set; }
        public bool ShowHiddenText { get; set; }
        public bool ShowTrackChanges { get; set; }
        public string SpreadSheetGridLine { get; set; }
        public bool ShowEmbeddedImages { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
