//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_MissingEmailGenerated
    {
        public long GeneratedEmailId { get; set; }
        public string BaseConversationId { get; set; }
        public string ConversationId { get; set; }
        public Nullable<long> SourceFileId { get; set; }
        public Nullable<int> RelativeThreadIndex { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> GroupDate { get; set; }
        public Nullable<System.DateTime> GroupDateGMT { get; set; }
        public string FulltextFileLocation { get; set; }
        public Nullable<long> FulltextFileSize { get; set; }
        public string Subject { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<System.DateTime> DateSentGMT { get; set; }
        public string Attachments { get; set; }
        public string MessageClass { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public string MatchedHeader { get; set; }
    }
}
