//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_printlog
    {
        public int logid { get; set; }
        public Nullable<int> CustodianId { get; set; }
        public Nullable<int> MediaId { get; set; }
        public string FileId { get; set; }
        public string Parameters { get; set; }
        public string LogType { get; set; }
        public string LogText { get; set; }
        public Nullable<System.DateTime> LogedDate { get; set; }
    }
}
