//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jb_Search
    {
        public long JobSearchId { get; set; }
        public Nullable<long> JobId { get; set; }
        public Nullable<long> MediaId { get; set; }
        public Nullable<long> SearchJobExpressionId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsSearchCompleted { get; set; }
        public string ProcessingInstanceId { get; set; }
        public Nullable<System.DateTime> QueuedOn { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public bool HasError { get; set; }
    
        public virtual tbl_sh_SearchJobExpression tbl_sh_SearchJobExpression { get; set; }
    }
}
