//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VAR_ProfileReviewSetAssociation
    {
        public int ProfileID { get; set; }
        public long ReviewSetID { get; set; }
        public Nullable<int> ReviewSetTypeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tbl_rev_ReviewSetInfo tbl_rev_ReviewSetInfo { get; set; }
        public virtual tbl_VAR_ProfileInfo tbl_VAR_ProfileInfo { get; set; }
        public virtual tbl_VAR_ReviewSetTypeInfo tbl_VAR_ReviewSetTypeInfo { get; set; }
    }
}
