//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ann_AnnotationDetail
    {
        public int AnnotationId { get; set; }
        public string AnnotationUniqueId { get; set; }
        public int ObjectId { get; set; }
        public long FileId { get; set; }
        public int UserId { get; set; }
        public int PageNumber { get; set; }
        public string RedactionXML { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
