//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_qc_DocSetFileAssociation
    {
        public long QCDocSetId { get; set; }
        public long FileId { get; set; }
        public Nullable<bool> IsQCCompleted { get; set; }
        public Nullable<bool> IsSkipped { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<long> CheckedOutBy { get; set; }
        public Nullable<System.DateTime> CheckedOutOn { get; set; }
        public Nullable<bool> IsCheckedOut { get; set; }
        public string QCFlags { get; set; }
    
        public virtual tbl_ex_FileInfo tbl_ex_FileInfo { get; set; }
        public virtual tbl_qc_DocSet tbl_qc_DocSet { get; set; }
    }
}
