//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_var_PredictionResultSummary
    {
        public long PredictionResultSummaryID { get; set; }
        public Nullable<long> ProfileId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> FloorPredictionScore { get; set; }
        public Nullable<long> JobId { get; set; }
        public Nullable<long> CountFileId { get; set; }
        public Nullable<bool> IsPredicted { get; set; }
    }
}
