//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_CrashedFileLog
    {
        public long Id { get; set; }
        public long CustodianId { get; set; }
        public long MediaId { get; set; }
        public string Filename { get; set; }
        public string AccessPath { get; set; }
        public string AbsoluteFilePath { get; set; }
        public long GroupId { get; set; }
        public string DumpLocation { get; set; }
        public long DumpStatus { get; set; }
        public string CrashReason { get; set; }
        public string LastUpdatedOriginalFilePath { get; set; }
        public Nullable<long> IngestionFileExpansionId { get; set; }
        public Nullable<long> ScanFileId { get; set; }
        public Nullable<long> ParentFileId { get; set; }
    }
}
