//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ig_MediaCopyStatus
    {
        public long ID { get; set; }
        public long custodianid { get; set; }
        public long mediaid { get; set; }
        public string sourcepath { get; set; }
        public string uploadpath { get; set; }
        public Nullable<bool> copycompleted { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<long> FileId { get; set; }
        public long MediaSourceAssociationId { get; set; }
        public string UniqueIdentifier { get; set; }
    }
}
