//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ann_AnnotationActionLog
    {
        public int AnnotationActionLogId { get; set; }
        public long FileId { get; set; }
        public int PageNo { get; set; }
        public int UserId { get; set; }
        public string AnnotationUniqueId { get; set; }
        public string AnnotationType { get; set; }
        public string Action { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string AnnotationDetail { get; set; }
        public Nullable<int> AnnotationId { get; set; }
        public string Module { get; set; }
    }
}
