//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jb_PromoteFileCopy
    {
        public long JobId { get; set; }
        public long SourceFileId { get; set; }
        public int Status { get; set; }
        public int FulltextStatus { get; set; }
        public long FulltextFileSize { get; set; }
        public int NativeStatus { get; set; }
        public long NativeFileSize { get; set; }
        public int TiffStatus { get; set; }
        public int TiffPageCount { get; set; }
        public long TiffFileSize { get; set; }
        public int TiffOcrStatus { get; set; }
        public int TiffOCRPageCount { get; set; }
        public long TiffOCRFileSize { get; set; }
        public int RedactedTiffOcrStatus { get; set; }
        public int RedactedTiffOCRPageCount { get; set; }
        public long RedactedTiffOCRFileSize { get; set; }
        public int DXLStatus { get; set; }
        public long DXLFileSize { get; set; }
        public int HtmlStatus { get; set; }
        public long HtmlFileSize { get; set; }
        public int RTFStatus { get; set; }
        public long RTFFileSize { get; set; }
        public string ProcessingInstanceId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> ReTryCount { get; set; }
    }
}
