//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_del_DeletionDuplicationChanges
    {
        public long BatchId { get; set; }
        public Nullable<long> MediaID { get; set; }
        public Nullable<long> FileID { get; set; }
        public Nullable<long> OriginalGroupID { get; set; }
    }
}
