//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_su_languagesummary
    {
        public Nullable<long> custodianid { get; set; }
        public long mediaid { get; set; }
        public string Language { get; set; }
        public Nullable<long> LanguageCount { get; set; }
    }
}
