//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_FilteredDocs
    {
        public long CustodianId { get; set; }
        public long MediaId { get; set; }
        public long FileId { get; set; }
        public string FileName { get; set; }
        public string AbsoluteFilePath { get; set; }
        public string RelativeFilePath { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string Extension { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> GroupDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdateOn { get; set; }
        public string FilterType { get; set; }
        public Nullable<long> FileInfoParentFileId { get; set; }
        public bool IsArchive { get; set; }
        public string OriginalFileExtension { get; set; }
        public Nullable<System.DateTime> GroupDateGMT { get; set; }
        public Nullable<long> ScanFileId { get; set; }
    }
}
