//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rev_FileInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_rev_FileInfo()
        {
            this.tbl_cmt_CommentFileReference = new HashSet<tbl_cmt_CommentFileReference>();
            this.tbl_lg_AutoCollectedFileLog = new HashSet<tbl_lg_AutoCollectedFileLog>();
            this.tbl_rev_BatchFileAssociation = new HashSet<tbl_rev_BatchFileAssociation>();
            this.tbl_rev_ReviewSet = new HashSet<tbl_rev_ReviewSet>();
        }
    
        public long ImportLogId { get; set; }
        public long FileId { get; set; }
        public long ParentFileId { get; set; }
        public long GroupId { get; set; }
        public string EntryId { get; set; }
        public bool IsDuplicate { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public long OriginalGroupId { get; set; }
        public bool IsCustodianLevelDuplicate { get; set; }
        public int DocumentType { get; set; }
        public int RecordType { get; set; }
        public string CustodianName { get; set; }
        public string HashValue { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string FileLanguage { get; set; }
        public string RelativeFilePath { get; set; }
        public string OriginalFilePath { get; set; }
        public Nullable<System.DateTime> GroupDate { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string Subject { get; set; }
        public string Attachment { get; set; }
        public string MessageId { get; set; }
        public string Sensitivity { get; set; }
        public string Importance { get; set; }
        public Nullable<System.DateTime> DateSentGMT { get; set; }
        public string Author { get; set; }
        public string Title { get; set; }
        public string DocSubject { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> FSLastAccessDateTime { get; set; }
        public Nullable<System.DateTime> FSCreatedDateTime { get; set; }
        public Nullable<System.DateTime> FSModifiedDateTime { get; set; }
        public Nullable<System.DateTime> LastSaveDateTime { get; set; }
        public string NativeFileLocation { get; set; }
        public string FullTextFileLocation { get; set; }
        public Nullable<bool> SheetHidden { get; set; }
        public Nullable<bool> SlideHidden { get; set; }
        public Nullable<bool> RowHidden { get; set; }
        public Nullable<bool> ColumnHidden { get; set; }
        public Nullable<bool> TrackChangeAdded { get; set; }
        public Nullable<bool> TrackChangeDeleted { get; set; }
        public Nullable<bool> HiddenText { get; set; }
        public Nullable<bool> HasHiddenObject { get; set; }
        public Nullable<System.DateTime> GroupDateGMT { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeGMT { get; set; }
        public Nullable<System.DateTime> FSLastAccessDateTimeGMT { get; set; }
        public Nullable<System.DateTime> FSCreatedDateTimeGMT { get; set; }
        public Nullable<System.DateTime> FSModifiedDateTimeGMT { get; set; }
        public Nullable<System.DateTime> LastSaveDateTimeGMT { get; set; }
        public string GroupHashValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cmt_CommentFileReference> tbl_cmt_CommentFileReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_lg_AutoCollectedFileLog> tbl_lg_AutoCollectedFileLog { get; set; }
        public virtual tbl_lg_ImportLog tbl_lg_ImportLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rev_BatchFileAssociation> tbl_rev_BatchFileAssociation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rev_ReviewSet> tbl_rev_ReviewSet { get; set; }
    }
}
