//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_PasswordBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ex_PasswordBank()
        {
            this.tbl_ig_PasswordReprocessLog = new HashSet<tbl_ig_PasswordReprocessLog>();
        }
    
        public long PasswordBankId { get; set; }
        public string Password { get; set; }
        public string NSFUserIdOriginalFilePath { get; set; }
        public string NSFUserIdFilePath { get; set; }
        public bool IsNSFUserIdFile { get; set; }
        public Nullable<long> MediaSourceAssociationId { get; set; }
    
        public virtual tbl_ex_MediaSourceAssociation tbl_ex_MediaSourceAssociation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ig_PasswordReprocessLog> tbl_ig_PasswordReprocessLog { get; set; }
    }
}
