//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jb_IngestionFileExpansion
    {
        public long IngestionFileExpansionId { get; set; }
        public long JobId { get; set; }
        public long ScanFileId { get; set; }
        public long ParentFileId { get; set; }
        public string NativeFilePath { get; set; }
        public Nullable<long> FileSize { get; set; }
        public int Status { get; set; }
        public string ProcessingInstanceId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public int RetryCount { get; set; }
        public string FileMeta { get; set; }
        public Nullable<long> FileReplacementFileId { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string CrashReason { get; set; }
        public string LastUpdatedOriginalFilePath { get; set; }
    }
}
