//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_CodingActionLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ex_CodingActionLog()
        {
            this.tbl_ex_CodingHistory = new HashSet<tbl_ex_CodingHistory>();
        }
    
        public long BatchCodingID { get; set; }
        public string CodingModule { get; set; }
        public long CodingBy { get; set; }
        public System.DateTime CodingAppliedDate { get; set; }
        public Nullable<long> TotalCodingCount { get; set; }
        public Nullable<long> SearchID { get; set; }
        public Nullable<long> ReviewBatchID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ex_CodingHistory> tbl_ex_CodingHistory { get; set; }
    }
}
