//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ocr_Language
    {
        public int LangID { get; set; }
        public string LangName { get; set; }
        public Nullable<bool> Enable { get; set; }
    }
}
