//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ep_ExportDetails
    {
        public long ExportID { get; set; }
        public long FileID { get; set; }
        public string ControlNumber { get; set; }
        public string BegDoc { get; set; }
        public string EndDoc { get; set; }
        public bool IsDerivedRecord { get; set; }
        public string FieldDetails { get; set; }
        public string OriginalControlNumber { get; set; }
        public string DuplicateCustodianNames { get; set; }
        public string DuplicateCustodianNamesAll { get; set; }
        public string DuplicateFilepath { get; set; }
        public string DuplicateFilepathAll { get; set; }
    }
}
