//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ep_TiffExportDetails
    {
        public long ExportID { get; set; }
        public long FileID { get; set; }
        public string BatesNumber { get; set; }
        public long PageNumber { get; set; }
        public string PreservedExportLocation { get; set; }
        public bool IsExcludedTiff { get; set; }
        public bool IsPlaceholderTiff { get; set; }
        public string TiffFieldDetails { get; set; }
        public Nullable<long> ImageSize { get; set; }
        public int ImagePageCount { get; set; }
        public string ImagePath { get; set; }
        public string Volume { get; set; }
        public Nullable<long> PageNumberForFamilyHandling { get; set; }
        public Nullable<bool> IsNativePlaceHolderFile { get; set; }
        public Nullable<bool> HasRedaction { get; set; }
        public string PdfPath { get; set; }
    }
}
