//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VAR_Model_Files
    {
        public int ProfileID { get; set; }
        public string ModelFile { get; set; }
        public string ProcessingID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tbl_VAR_ProfileInfo tbl_VAR_ProfileInfo { get; set; }
    }
}
