//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fd_FolderHierarchy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_fd_FolderHierarchy()
        {
            this.tbl_fd_folderHistory = new HashSet<tbl_fd_folderHistory>();
        }
    
        public long FolderID { get; set; }
        public string FolderName { get; set; }
        public long ParentFolderID { get; set; }
        public string FolderLineage { get; set; }
        public string FolderIDLineage { get; set; }
        public long FileCount { get; set; }
        public string AccessType { get; set; }
        public bool IsSystemFolder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_fd_folderHistory> tbl_fd_folderHistory { get; set; }
    }
}
