//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fd_DynamicFolderPrjGrpAsso
    {
        public long DynamicFolderProjectGroupAssociationId { get; set; }
        public long DynamicFolderId { get; set; }
        public string GroupId { get; set; }
        public string DynamicFolderPermission { get; set; }
        public bool IsGlobal { get; set; }
    }
}
