//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_MediaSourceAssociation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ex_MediaSourceAssociation()
        {
            this.tbl_ex_PasswordBank = new HashSet<tbl_ex_PasswordBank>();
        }
    
        public long MediaSourceAssociationId { get; set; }
        public long MediaId { get; set; }
        public string Source { get; set; }
        public string BaseFolder { get; set; }
        public string SourceType { get; set; }
        public long SourceFSID { get; set; }
        public string ConnectionSettings { get; set; }
        public string SelectionSettings { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ex_PasswordBank> tbl_ex_PasswordBank { get; set; }
    }
}
