//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rev_ReviewSetInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_rev_ReviewSetInfo()
        {
            this.tbl_lg_AutoCollectionLog = new HashSet<tbl_lg_AutoCollectionLog>();
            this.tbl_rev_EmailAlertReceiver = new HashSet<tbl_rev_EmailAlertReceiver>();
            this.tbl_rev_ReviewBatch = new HashSet<tbl_rev_ReviewBatch>();
            this.tbl_rev_ReviewerSettings = new HashSet<tbl_rev_ReviewerSettings>();
            this.tbl_rev_ReviewSet = new HashSet<tbl_rev_ReviewSet>();
            this.tbl_rev_UserReviewAssociation = new HashSet<tbl_rev_UserReviewAssociation>();
            this.tbl_rev_ReviewSetInfo1 = new HashSet<tbl_rev_ReviewSetInfo>();
            this.tbl_rev_TagGroupSortOrder = new HashSet<tbl_rev_TagGroupSortOrder>();
            this.tbl_rev_TagSortOrder = new HashSet<tbl_rev_TagSortOrder>();
            this.tbl_VAR_ProfileReviewSetAssociation = new HashSet<tbl_VAR_ProfileReviewSetAssociation>();
        }
    
        public long ReviewSetId { get; set; }
        public string ReviewSource { get; set; }
        public bool ParentChildIncluded { get; set; }
        public bool MessageThreadIncluded { get; set; }
        public bool ExcludePreviousReviewSetDoc { get; set; }
        public bool NearDupsIncluded { get; set; }
        public int TagPropagationOption { get; set; }
        public bool TagPropagatePcSet { get; set; }
        public bool TagPropagateEmailThread { get; set; }
        public Nullable<long> SavedSearchId { get; set; }
        public string TagId { get; set; }
        public string FolderId { get; set; }
        public string TagSelectionOption { get; set; }
        public string FolderSelectionOption { get; set; }
        public string Name { get; set; }
        public string BatchPrefix { get; set; }
        public long BatchSize { get; set; }
        public long BatchStartNumber { get; set; }
        public long BatchPaddingLength { get; set; }
        public string Purpose { get; set; }
        public bool ShowPurposeInUI { get; set; }
        public long ReviewTagId { get; set; }
        public bool EnableAutoCollect { get; set; }
        public string ReviewSetJobName { get; set; }
        public int AutoCollectThresholdValue { get; set; }
        public Nullable<int> AutoCollectFrequency { get; set; }
        public Nullable<System.DateTime> AutoCollectExpiresOn { get; set; }
        public Nullable<bool> SendEmailAfterAutoCollection { get; set; }
        public string AutoCollectEmailSubject { get; set; }
        public string AutoCollectEmailBody { get; set; }
        public string ReviewCreationEmailSubject { get; set; }
        public string ReviewCreationEmailBody { get; set; }
        public bool SendEmailAfterReviewCreation { get; set; }
        public Nullable<long> SourceReviewSetId { get; set; }
        public long ReviewSetStatus { get; set; }
        public string OrderByField { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public bool isPublished { get; set; }
        public string ReviewerVisibleOption { get; set; }
        public bool ShowEmailHeaderInFulltext { get; set; }
        public Nullable<long> AutoCollectDependentReviewSet { get; set; }
        public string SampleId { get; set; }
        public string SampleSelectionOption { get; set; }
        public int ReviewType { get; set; }
        public string PredictionID { get; set; }
        public int DuplicateReviewPropagationOption { get; set; }
        public bool ReviewPropagateEmailThread { get; set; }
        public bool ReviewPropagatePcSet { get; set; }
        public string RedactionObjectId { get; set; }
        public bool ShowHideReviewedFiles { get; set; }
        public bool EnforceTagForReview { get; set; }
        public Nullable<long> ReviewSetTemplateId { get; set; }
        public bool AutoQueueForHtmlConversion { get; set; }
        public bool AutoQueueForTiff { get; set; }
        public bool ExcludeNonInclusiveEmails { get; set; }
        public string TagGroupIdsForTagGroupRule { get; set; }
        public string DynamicFolderId { get; set; }
        public string TagRules { get; set; }
    
        public virtual tbl_ex_tag tbl_ex_tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_lg_AutoCollectionLog> tbl_lg_AutoCollectionLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rev_EmailAlertReceiver> tbl_rev_EmailAlertReceiver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rev_ReviewBatch> tbl_rev_ReviewBatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rev_ReviewerSettings> tbl_rev_ReviewerSettings { get; set; }
        public virtual Tbl_Rev_ReviewerWorkSchedule Tbl_Rev_ReviewerWorkSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rev_ReviewSet> tbl_rev_ReviewSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rev_UserReviewAssociation> tbl_rev_UserReviewAssociation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rev_ReviewSetInfo> tbl_rev_ReviewSetInfo1 { get; set; }
        public virtual tbl_rev_ReviewSetInfo tbl_rev_ReviewSetInfo2 { get; set; }
        public virtual tbl_fld_AvailableReviewField tbl_fld_AvailableReviewField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rev_TagGroupSortOrder> tbl_rev_TagGroupSortOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rev_TagSortOrder> tbl_rev_TagSortOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VAR_ProfileReviewSetAssociation> tbl_VAR_ProfileReviewSetAssociation { get; set; }
    }
}
