//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jb_SkippedJobFiles
    {
        public long Id { get; set; }
        public string JobType { get; set; }
        public long JobId { get; set; }
        public long FileID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual tbl_ds_ProjectJobInfo tbl_ds_ProjectJobInfo { get; set; }
        public virtual tbl_ex_FileInfo tbl_ex_FileInfo { get; set; }
    }
}
