//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pj_GroupInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_pj_GroupInfo()
        {
            this.tbl_fld_GroupFieldAssociation = new HashSet<tbl_fld_GroupFieldAssociation>();
            this.tbl_pj_GroupRightAssociation = new HashSet<tbl_pj_GroupRightAssociation>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
        public bool IsSystem { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public bool IsGroupDeactivated { get; set; }
        public bool IsDocRestricted { get; set; }
        public string AdGroup { get; set; }
        public string IDPGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_fld_GroupFieldAssociation> tbl_fld_GroupFieldAssociation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pj_GroupRightAssociation> tbl_pj_GroupRightAssociation { get; set; }
        public virtual tbl_pj_GroupUserAssociation tbl_pj_GroupUserAssociation { get; set; }
    }
}
