//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_an_EmailNodes
    {
        public long EmailNodeID { get; set; }
        public Nullable<long> CustodianId { get; set; }
        public Nullable<long> MediaId { get; set; }
        public string EmailAddress { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string DomainName { get; set; }
        public Nullable<bool> InternalDomainFlag { get; set; }
        public Nullable<long> MsgSentCount { get; set; }
        public Nullable<long> MsgReceivedCount { get; set; }
        public string UnParsedEmail { get; set; }
    }
}
