//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_qc_UserFieldAssociation
    {
        public long UserId { get; set; }
        public long FieldId { get; set; }
        public bool IsDisplayed { get; set; }
        public long OrderWeight { get; set; }
    }
}
