//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ig_WarningLog
    {
        public long WarningId { get; set; }
        public long CustodianId { get; set; }
        public long MediaId { get; set; }
        public long FileId { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public System.DateTime LoggedDate { get; set; }
    }
}
