//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_EdocMeta
    {
        public long FileID { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string Company { get; set; }
        public string Title { get; set; }
        public string LastAuthor { get; set; }
        public Nullable<System.DateTime> LastSaveDateTime { get; set; }
        public bool SheetHidden { get; set; }
        public bool SlideHidden { get; set; }
        public bool RowHidden { get; set; }
        public bool ColumnHidden { get; set; }
        public bool trackChangeAdded { get; set; }
        public bool TrackChangeDeleted { get; set; }
        public bool Hiddentext { get; set; }
        public string RevisionNumber { get; set; }
        public string Keywords { get; set; }
        public Nullable<System.DateTime> LastPrintedOn { get; set; }
        public string Subject { get; set; }
        public string Category { get; set; }
        public string Comments { get; set; }
        public string CreatingApplication { get; set; }
        public Nullable<long> PageCount { get; set; }
        public Nullable<long> WordCount { get; set; }
        public Nullable<long> CharacterCount { get; set; }
        public Nullable<long> LineCount { get; set; }
        public Nullable<long> ParagraphCount { get; set; }
        public Nullable<System.DateTime> CreateDateTimeGMT { get; set; }
        public Nullable<System.DateTime> LastSaveDateTimeGMT { get; set; }
        public Nullable<System.DateTime> LastPrintedOnGMT { get; set; }
        public string PictureTakenLocation { get; set; }
        public Nullable<bool> HasSpeakerNote { get; set; }
        public bool HasVeryHiddenSheet { get; set; }
        public bool HasCroppedContent { get; set; }
        public bool HasComments { get; set; }
        public Nullable<bool> HasMacrosAndCode { get; set; }
        public Nullable<bool> HasHeadersFooters { get; set; }
    }
}
