//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sm_sampletagtrackinfo
    {
        public long SampleID { get; set; }
        public long Fileid { get; set; }
        public long Mediaid { get; set; }
        public long CustodianID { get; set; }
        public long TagBatchID { get; set; }
        public Nullable<bool> TrackFor { get; set; }
    }
}
