//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cmt_Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cmt_Comment()
        {
            this.tbl_cmt_CommentFileReference = new HashSet<tbl_cmt_CommentFileReference>();
        }
    
        public long CommentId { get; set; }
        public Nullable<long> BatchId { get; set; }
        public long FileId { get; set; }
        public Nullable<int> CommentedBy { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Comment { get; set; }
        public string CommentTextOnly { get; set; }
        public Nullable<long> InReplyToCommentId { get; set; }
        public Nullable<long> ReviewSetId { get; set; }
        public bool IsDeleted { get; set; }
        public string Accessibility { get; set; }
        public Nullable<int> ExternalUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cmt_CommentFileReference> tbl_cmt_CommentFileReference { get; set; }
    }
}
