//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_var_ControlSetLog
    {
        public long ControlSetLogId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public string PredictionId { get; set; }
        public string TrainingModelId { get; set; }
        public Nullable<int> ControlSetDoc { get; set; }
        public Nullable<double> Precision { get; set; }
        public Nullable<double> Recall { get; set; }
        public Nullable<double> F1Score { get; set; }
    }
}
