//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ex_NativeReplacement
    {
        public long ImportId { get; set; }
        public Nullable<long> CustodiaId { get; set; }
        public Nullable<long> MediaId { get; set; }
        public long FileId { get; set; }
        public string BackUpFilePath { get; set; }
    }
}
