//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pr_FileInfoPromoteFileAssociation
    {
        public long FileId { get; set; }
        public Nullable<long> SourceFileId { get; set; }
        public Nullable<long> SourceParentFileId { get; set; }
        public Nullable<bool> SourceIsParent { get; set; }
        public Nullable<long> SourceGroupId { get; set; }
        public Nullable<bool> SourceIsDuplicate { get; set; }
        public Nullable<bool> SourceIsDuplicateCustodianLevel { get; set; }
        public Nullable<long> SourceOriginalGroupId { get; set; }
        public Nullable<long> SourceProjectId { get; set; }
        public Nullable<long> PromoteId { get; set; }
        public Nullable<long> JobId { get; set; }
    }
}
