//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rev_BatchFileAssociation
    {
        public long BatchFileAssocicationId { get; set; }
        public long BatchId { get; set; }
        public long FileId { get; set; }
    
        public virtual tbl_rev_ReviewBatch tbl_rev_ReviewBatch { get; set; }
        public virtual tbl_rev_FileInfo tbl_rev_FileInfo { get; set; }
    }
}
