//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pj_GroupRightAssociation
    {
        public int GroupId { get; set; }
        public int RightId { get; set; }
    
        public virtual tbl_pj_GroupInfo tbl_pj_GroupInfo { get; set; }
    }
}
