//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fld_RevDisplayCodingFields
    {
        public long CodingFieldId { get; set; }
        public string FieldName { get; set; }
        public Nullable<long> ReviewSetId { get; set; }
        public int OrderWeight { get; set; }
    }
}
