//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_HTMLFileLocation
    {
        public long CustodianId { get; set; }
        public long MediaId { get; set; }
        public long FileId { get; set; }
        public string HTMLFileLocation { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string MHTFileLocation { get; set; }
        public Nullable<long> HtmlFileSize { get; set; }
        public bool IsFileSplitted { get; set; }
    }
}
