//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_EmailAddresses
    {
        public long EmailAddressID { get; set; }
        public long CustodianId { get; set; }
        public long MediaId { get; set; }
        public long FileID { get; set; }
        public long SenderID { get; set; }
        public long RecepientID { get; set; }
        public int Category { get; set; }
        public Nullable<System.DateTime> GroupDate { get; set; }
        public long oldSenderId { get; set; }
        public long oldRecepientId { get; set; }
    }
}
