//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_ReplacementJob
    {
        public long Id { get; set; }
        public Nullable<long> CustodianId { get; set; }
        public Nullable<long> MediaId { get; set; }
        public Nullable<long> FileId { get; set; }
        public string ReplacementFile { get; set; }
        public string ReplacementType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public string ProcessingInstanceId { get; set; }
        public Nullable<long> JobId { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> IsFileExpansionCompleted { get; set; }
        public Nullable<long> PasswordBankId { get; set; }
        public bool IsReprocess { get; set; }
    }
}
