//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_EmailMeta
    {
        public long FileID { get; set; }
        public string RelativePath { get; set; }
        public string MessageID { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<System.DateTime> DateSentGMT { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DateReceivedGMT { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Attachments { get; set; }
        public string EntryId { get; set; }
        public string ConversationId { get; set; }
        public string Sensitivity { get; set; }
        public string Importance { get; set; }
        public Nullable<System.DateTime> MeetingStartGMT { get; set; }
        public Nullable<System.DateTime> MeetingEndGMT { get; set; }
        public string MessageClass { get; set; }
        public Nullable<bool> EmailReplied { get; set; }
        public string EmailRepliedTo { get; set; }
        public Nullable<System.DateTime> EmailRepliedDateTimeGMT { get; set; }
        public Nullable<bool> UnRead { get; set; }
        public Nullable<bool> ReadReceiptRequested { get; set; }
        public Nullable<bool> DeliveryReceiptRequested { get; set; }
        public string Categories { get; set; }
        public string NormalizedSubject { get; set; }
        public string NsfUNID { get; set; }
        public string InReplyTo { get; set; }
        public string References { get; set; }
        public Nullable<bool> HasOnBehalfOfEmail { get; set; }
        public string OnBehalfOfEmail { get; set; }
        public Nullable<System.DateTime> CreationTimeGMT { get; set; }
        public Nullable<System.DateTime> LastModifiedTimeGMT { get; set; }
        public Nullable<System.DateTime> MeetingStart { get; set; }
        public Nullable<System.DateTime> MeetingEnd { get; set; }
        public Nullable<System.DateTime> EmailRepliedDateTime { get; set; }
        public string HashMeta { get; set; }
        public string InternetMessageHeader { get; set; }
    }
}
