//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_InclusiveEmailDetails
    {
        public long FileId { get; set; }
        public bool IsLeafNode { get; set; }
        public bool IsAttachmentChange { get; set; }
        public string AttachmentHashValue { get; set; }
        public bool IsTextChange { get; set; }
    }
}
