//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ep_ExportPrimaryTable
    {
        public long ExportID { get; set; }
        public long SEQ_NO { get; set; }
        public long FILE_ID_PK { get; set; }
        public Nullable<long> GROUPID { get; set; }
        public string CONTROLNUMBER { get; set; }
        public Nullable<bool> DERIVEDDATA { get; set; }
        public Nullable<int> FOLDER_SEQ_NO { get; set; }
        public string Original_Export_Native_Path { get; set; }
        public string Original_Export_Fulltext_Path { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public string Original_Export_File_Name { get; set; }
        public string Original_Export_Fulltext_Type { get; set; }
        public Nullable<int> Original_Image_Page_Count { get; set; }
        public string Original_Is_Native_Missing { get; set; }
        public int CopyStatus { get; set; }
        public string CopyProcessingInstanceId { get; set; }
        public string OriginalControlNumber { get; set; }
        public string RetryField { get; set; }
        public Nullable<bool> Original_Has_Redaction { get; set; }
        public string OriginalFilePath { get; set; }
    }
}
