//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VAR_TF_Files
    {
        public string TrainingItemID { get; set; }
        public string TFFile { get; set; }
        public int profileID { get; set; }
        public Nullable<int> categoryID { get; set; }
    
        public virtual tbl_VAR_ProfileInfo tbl_VAR_ProfileInfo { get; set; }
    }
}
