//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_tiff_Images
    {
        public long MediaId { get; set; }
        public long FileId { get; set; }
        public string ImagePath { get; set; }
        public long Pagenumber { get; set; }
        public long ImageSize { get; set; }
        public Nullable<bool> IsSlipSheet { get; set; }
        public string SlipSheetText { get; set; }
        public string RedactedImagePath { get; set; }
        public Nullable<System.DateTime> RedactedImageDate { get; set; }
        public Nullable<bool> IsRedactionSuccessful { get; set; }
        public string SystemBatesNumber { get; set; }
        public bool IsColoredTiff { get; set; }
        public bool IsCutoff { get; set; }
        public long CutoffOption { get; set; }
    }
}
