//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_IngestionBookmark
    {
        public long Id { get; set; }
        public long CustodianId { get; set; }
        public long MediaId { get; set; }
        public string Filename { get; set; }
        public string AccessPath { get; set; }
        public string AbsoluteFilePath { get; set; }
        public bool AccessFlag { get; set; }
        public bool FileCompleteFlag { get; set; }
        public long MediaSourceAssociationId { get; set; }
        public string UniqueIdentifier { get; set; }
        public string TempProcessingPath { get; set; }
        public Nullable<long> ScanFileId { get; set; }
        public string ProcessingStatus { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string CrashReason { get; set; }
        public string LastUpdatedOriginalFilePath { get; set; }
        public Nullable<bool> IsFirstLevelFile { get; set; }
        public Nullable<long> LastParentFileId { get; set; }
    }
}
