//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_EmailNameInfo
    {
        public long EmailNameId { get; set; }
        public string EmailName { get; set; }
        public string EmailAddress { get; set; }
        public string Domain { get; set; }
        public long EmailNameFreq { get; set; }
        public long LCSLength { get; set; }
        public long CharCount { get; set; }
        public decimal NonGarbageScore { get; set; }
    }
}
