//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pj_FileTypeRestriction
    {
        public long Seq_No { get; set; }
        public bool InclusiveFlag { get; set; }
        public string RestrictionType { get; set; }
        public string RestrictionItem { get; set; }
        public string Extension { get; set; }
    }
}
