//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rev_ReviewSet
    {
        public long ReviewSetId { get; set; }
        public long FileId { get; set; }
        public bool IsDerivedRecord { get; set; }
        public long ReviewSetFileOrderId { get; set; }
    
        public virtual tbl_rev_FileInfo tbl_rev_FileInfo { get; set; }
        public virtual tbl_rev_ReviewSetInfo tbl_rev_ReviewSetInfo { get; set; }
    }
}
