//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_SavedSearchResults
    {
        public long SaveSearchID { get; set; }
        public long Custodianid { get; set; }
        public long Mediaid { get; set; }
        public long Fileid { get; set; }
        public long SearchID { get; set; }
        public long TermId { get; set; }
        public Nullable<double> Score { get; set; }
    }
}
