//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_FulltextReplacement
    {
        public long ReplacementID { get; set; }
        public long CustodianID { get; set; }
        public long MediaID { get; set; }
        public long FileID { get; set; }
        public Nullable<long> BatchReplacementID { get; set; }
        public string ReplacementFileLocation { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
