//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ig_ExceptionLog
    {
        public long ErrorId { get; set; }
        public long CustodianId { get; set; }
        public long MediaId { get; set; }
        public Nullable<System.DateTime> ExceptionDateTime { get; set; }
        public string ExceptionType { get; set; }
        public string ExceptionMessage { get; set; }
        public string ExceptionTargetSite { get; set; }
        public string ExceptionStackTrace { get; set; }
    }
}
