//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lg_ProcessLog
    {
        public long ProcessLogId { get; set; }
        public long CustodianId { get; set; }
        public long MediaId { get; set; }
        public Nullable<System.DateTime> ProcessStartTime { get; set; }
        public Nullable<System.DateTime> ProcessEndTime { get; set; }
        public Nullable<int> SuccessFlag { get; set; }
        public string ProcessException { get; set; }
        public string ProcessType { get; set; }
        public Nullable<long> IngestionJobId { get; set; }
    }
}
