//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tg_TagProjectGroupAssociation
    {
        public long TagProjectGroupAssociationId { get; set; }
        public long TagID { get; set; }
        public long GroupId { get; set; }
        public bool ReadPermission { get; set; }
        public bool WritePermission { get; set; }
    }
}
