//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jb_ImportLoadFileFormat
    {
        public long LoadFileFormatId { get; set; }
        public string LoadFileFormatName { get; set; }
        public Nullable<int> FieldSeparator { get; set; }
        public Nullable<int> TextQualifier { get; set; }
        public Nullable<int> LineBreak { get; set; }
        public string FileType { get; set; }
    }
}
