//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rev_ReviewerSettings
    {
        public long ReviewSetId { get; set; }
        public long UserId { get; set; }
        public Nullable<long> SortByFieldId1 { get; set; }
        public string SortOrderField1 { get; set; }
        public Nullable<bool> IsCustomField1 { get; set; }
        public Nullable<long> SortByFieldId2 { get; set; }
        public string SortOrderField2 { get; set; }
        public Nullable<bool> IsCustomField2 { get; set; }
        public Nullable<long> SortByFieldId3 { get; set; }
        public string SortOrderField3 { get; set; }
        public Nullable<bool> IsCustomField3 { get; set; }
        public bool SortKeepPCTogether { get; set; }
    
        public virtual tbl_rev_ReviewSetInfo tbl_rev_ReviewSetInfo { get; set; }
    }
}
