//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_qc_Note
    {
        public long CommentId { get; set; }
        public Nullable<long> FileId { get; set; }
        public string Comment { get; set; }
        public Nullable<long> CommentedBy { get; set; }
        public Nullable<System.DateTime> CommentedOn { get; set; }
        public string QCType { get; set; }
    }
}
