//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_searchserverlog
    {
        public long LogId { get; set; }
        public long MediaId { get; set; }
        public string Term { get; set; }
        public string SearchServer { get; set; }
        public string Remark { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> SearchEndDateTime { get; set; }
        public Nullable<long> SearchId { get; set; }
        public Nullable<System.DateTime> SearchStartDateTime { get; set; }
    }
}
