//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_qc_DocSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_qc_DocSet()
        {
            this.tbl_qc_DocSetFileAssociation = new HashSet<tbl_qc_DocSetFileAssociation>();
        }
    
        public long QCDocSetId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string QCType { get; set; }
        public Nullable<long> DocBatchSize { get; set; }
        public Nullable<long> MaxBatchPageLimit { get; set; }
        public Nullable<int> DocSetStatus { get; set; }
        public string TagId { get; set; }
        public string FolderId { get; set; }
        public string SearchId { get; set; }
        public string MediaId { get; set; }
        public string TagSelectionOption { get; set; }
        public string FolderSelectionOption { get; set; }
        public string FileType { get; set; }
        public string QCDocSetName { get; set; }
        public string QCDocSetSource { get; set; }
        public string SelectedFlags { get; set; }
        public Nullable<bool> IsPreviousQcDocumentExcluded { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_qc_DocSetFileAssociation> tbl_qc_DocSetFileAssociation { get; set; }
    }
}
