//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VAR_CG_shadow
    {
        public long CGSetID { get; set; }
        public Nullable<long> JobID { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public Nullable<int> MinC { get; set; }
        public Nullable<int> MaxC { get; set; }
        public Nullable<int> CStep { get; set; }
        public Nullable<int> MinG { get; set; }
        public Nullable<int> MaxG { get; set; }
        public Nullable<int> GStep { get; set; }
        public string ProcessingID { get; set; }
        public Nullable<int> ProcessingFlag { get; set; }
        public Nullable<int> ErrorType { get; set; }
        public Nullable<double> ResultAccuracy { get; set; }
        public Nullable<double> BestCInBatch { get; set; }
        public Nullable<double> BestGInBatch { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> CGBatchStartedDate { get; set; }
        public Nullable<System.DateTime> CGBatchCompletedDate { get; set; }
        public long RetryCount { get; set; }
    
        public virtual tbl_ds_ProjectJobInfo tbl_ds_ProjectJobInfo { get; set; }
    }
}
