//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cmt_CommentFileReference
    {
        public long CommentFileRefId { get; set; }
        public long CommentId { get; set; }
        public long FileId { get; set; }
    
        public virtual tbl_cmt_Comment tbl_cmt_Comment { get; set; }
        public virtual tbl_rev_FileInfo tbl_rev_FileInfo { get; set; }
    }
}
