//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ep_ExportTiffPrimaryTable
    {
        public long ExportID { get; set; }
        public Nullable<long> Seq_No { get; set; }
        public long File_Id_PK { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string BatesNumber { get; set; }
        public string Image_Path { get; set; }
        public int Page_Number { get; set; }
        public string Redacted_Image_Path { get; set; }
        public Nullable<int> FolderId { get; set; }
        public string Original_Export_Image_Path { get; set; }
    }
}
