//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_MissingEmailParserRegex
    {
        public int RegexID { get; set; }
        public string RegexString { get; set; }
        public string Description { get; set; }
        public bool IsEnabled { get; set; }
    }
}
