//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ep_ExportArchiveInfo
    {
        public long ExportId { get; set; }
        public string OriginalArchiveLocation { get; set; }
        public string ManualArchiveLocation { get; set; }
        public Nullable<long> OriginalArchiveFileSize { get; set; }
        public Nullable<long> ManualArchiveFileSize { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
