//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lg_AutoCollectionLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_lg_AutoCollectionLog()
        {
            this.tbl_lg_AutoCollectedFileLog = new HashSet<tbl_lg_AutoCollectedFileLog>();
        }
    
        public long AutoCollectionLogId { get; set; }
        public long ReviewSetId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_lg_AutoCollectedFileLog> tbl_lg_AutoCollectedFileLog { get; set; }
        public virtual tbl_rev_ReviewSetInfo tbl_rev_ReviewSetInfo { get; set; }
    }
}
