//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QC_PreQCImage
    {
        public long FileId { get; set; }
        public long PageNumber { get; set; }
        public Nullable<bool> IsPreQCErrored { get; set; }
        public Nullable<bool> IsRightCutOff { get; set; }
        public Nullable<bool> IsBlank { get; set; }
        public Nullable<bool> IsLittleContent { get; set; }
        public Nullable<bool> IsPageCountDiscrepancy { get; set; }
        public Nullable<bool> IsOnePageImage { get; set; }
        public Nullable<bool> IsTiffInaccessible { get; set; }
        public Nullable<bool> IsColorImage { get; set; }
    
        public virtual tbl_ex_FileInfo tbl_ex_FileInfo { get; set; }
    }
}
