//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VAR_PredictionResult
    {
        public long FileID { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<double> PredictionScore { get; set; }
        public Nullable<bool> IsPredicted { get; set; }
        public long JobID { get; set; }
    
        public virtual tbl_VAR_ProfileInfo tbl_VAR_ProfileInfo { get; set; }
    }
}
