//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ig_IngestionJobList
    {
        public long Id { get; set; }
        public long Custodianid { get; set; }
        public long MediaId { get; set; }
        public Nullable<long> IngestionJobId { get; set; }
        public string Operation { get; set; }
    }
}
