//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ep_ExportSecondaryTable
    {
        public long ExportId { get; set; }
        public long GroupId { get; set; }
        public string BegAtt { get; set; }
        public string EndAtt { get; set; }
        public string BegFamily { get; set; }
    }
}
