//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rev_CustomField
    {
        public long FileId { get; set; }
        public string DOCUMENT_UNIQUE_IDENTIFIER { get; set; }
        public string FAMILY_IDENTIFIER { get; set; }
        public string Priv_Type { get; set; }
        public string Priv_Title { get; set; }
        public string Priv_From { get; set; }
        public string Priv_To { get; set; }
    }
}
