//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ann_CustomStamp
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public string BackgroundColor { get; set; }
        public string ForeColor { get; set; }
        public int FontSize { get; set; }
    }
}
