//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fld_CustomFieldInfo
    {
        public long CustomFieldInfoId { get; set; }
        public string FieldName { get; set; }
        public string Description { get; set; }
        public string UIInputType { get; set; }
        public string ChoiceType { get; set; }
        public string ChoiceValues { get; set; }
        public string DefaultValue { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<bool> IsSearchable { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string DisplayName { get; set; }
        public bool AllowCoding { get; set; }
        public bool AllowMultipleCodingValues { get; set; }
        public string DelimiterForCodingValues { get; set; }
        public bool AllowPredefinedCodingValuesOnly { get; set; }
        public Nullable<long> Scale { get; set; }
        public Nullable<long> Length { get; set; }
        public string IndexName { get; set; }
        public Nullable<long> DisplaySequence { get; set; }
        public string DateFormat { get; set; }
    }
}
