//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VAR_ProfileGenericLogAssociation
    {
        public long LogAssociationID { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string TrainingItemID { get; set; }
        public Nullable<long> LogID { get; set; }
    }
}
