//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VAR_PredictionTrainingModelAssociation
    {
        public int ProfileID { get; set; }
        public long PredictionJobID { get; set; }
        public string PredictionID { get; set; }
        public string TrainingModelID { get; set; }
        public string PredictionNotes { get; set; }
    }
}
