//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_en_auditlog
    {
        public long AuditLogID { get; set; }
        public Nullable<long> EmailNotificationId { get; set; }
        public Nullable<int> EventID { get; set; }
        public string EmailRecepient { get; set; }
        public Nullable<System.DateTime> logdate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> MsDbMailItemID { get; set; }
        public Nullable<int> ActualSenderID { get; set; }
        public string EmailSender { get; set; }
        public string Subject { get; set; }
        public string Attachements { get; set; }
        public string EmailBody { get; set; }
    }
}
