//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_CodingHistory
    {
        public long ID { get; set; }
        public long BatchCodingID { get; set; }
        public long FileID { get; set; }
        public Nullable<long> CodingFieldID { get; set; }
        public string CodingValue { get; set; }
        public string CodingAction { get; set; }
    
        public virtual tbl_ex_CodingActionLog tbl_ex_CodingActionLog { get; set; }
    }
}
