//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_su_medialevelcountsummary
    {
        public long CustodianID { get; set; }
        public long MediaID { get; set; }
        public long TotalProcessedCount { get; set; }
        public long FileTypeRestrictedCount { get; set; }
        public long FileExtensionRestrictedCount { get; set; }
        public long DateRestrictedCount { get; set; }
        public long DeNISTCount { get; set; }
        public long SystemFilesCount { get; set; }
        public long PasswordProtectedArchiveCount { get; set; }
        public long CorruptedArchiveCount { get; set; }
        public long NonProcessedArchiveCount { get; set; }
        public long ProcessedArchiveCount { get; set; }
        public long OriginalProcessedEmailCount { get; set; }
        public long OriginalProcessedAttachmentCount { get; set; }
        public long DuplicateProcessedEmailCount { get; set; }
        public long DuplicateProcessedAttachmentCount { get; set; }
        public long OriginalProcessedEdocCount { get; set; }
        public long OriginalProcessedEmbeddedEdocCount { get; set; }
        public long DuplicateProcessedEdocCount { get; set; }
        public long DuplicateProcessedEmbeddedEdocCount { get; set; }
        public long OriginalPasswordProtectedEmailCount { get; set; }
        public long OriginalPasswordProtectedAttachmentCount { get; set; }
        public long DuplicatePasswordProtectedEmailCount { get; set; }
        public long DuplicatePasswordProtectedAttachmentCount { get; set; }
        public long OriginalPasswordProtectedEdocCount { get; set; }
        public long OriginalPasswordProtectedEmbeddedEdocCount { get; set; }
        public long DuplicatePasswordProtectedEdocCount { get; set; }
        public long DuplicatePasswordProtectedEmbeddedEdocCount { get; set; }
        public long OriginalCorruptedEmailCount { get; set; }
        public long OriginalCorruptedAttachmentCount { get; set; }
        public long DuplicateCorruptedEmailCount { get; set; }
        public long DuplicateCorruptedAttachmentCount { get; set; }
        public long OriginalCorruptedEdocCount { get; set; }
        public long OriginalCorruptedEmbeddedEdocCount { get; set; }
        public long DuplicateCorruptedEdocCount { get; set; }
        public long DuplicateCorruptedEmbeddedEdocCount { get; set; }
        public long OriginalUnknownEmailCount { get; set; }
        public long OriginalUnknownAttachmentCount { get; set; }
        public long DuplicateUnknownEmailCount { get; set; }
        public long DuplicateUnknownAttachmentCount { get; set; }
        public long OriginalUnknownEdocCount { get; set; }
        public long OriginalUnknownEmbeddedEdocCount { get; set; }
        public long DuplicateUnknownEdocCount { get; set; }
        public long DuplicateUnknownEmbeddedEdocCount { get; set; }
        public long OriginalProcessingErrorEmailCount { get; set; }
        public long OriginalProcessingErrorAttachmentCount { get; set; }
        public long DuplicateProcessingErrorEmailCount { get; set; }
        public long DuplicateProcessingErrorAttachmentCount { get; set; }
        public long OriginalProcessingErrorEdocCount { get; set; }
        public long OriginalProcessingErrorEmbeddedEdocCount { get; set; }
        public long DuplicateProcessingErrorEdocCount { get; set; }
        public long DuplicateProcessingErrorEmbeddedEdocCount { get; set; }
        public Nullable<System.DateTime> MinEmailGroupDate { get; set; }
        public Nullable<System.DateTime> MaxEmailGroupDate { get; set; }
        public Nullable<System.DateTime> MinEdocGroupDate { get; set; }
        public Nullable<System.DateTime> MaxEdocGroupDate { get; set; }
        public long CustodianDuplicateProcessedEmailCount { get; set; }
        public long CustodianDuplicateProcessedAttachmentCount { get; set; }
        public long CustodianDuplicateProcessedEdocCount { get; set; }
        public long CustodianDuplicateProcessedEmbeddedEdocCount { get; set; }
        public long CustodianDuplicatePasswordProtectedEmailCount { get; set; }
        public long CustodianDuplicatePasswordProtectedAttachmentCount { get; set; }
        public long CustodianDuplicatePasswordProtectedEdocCount { get; set; }
        public long CustodianDuplicatePasswordProtectedEmbeddedEdocCount { get; set; }
        public long CustodianDuplicateCorruptedEmailCount { get; set; }
        public long CustodianDuplicateCorruptedAttachmentCount { get; set; }
        public long CustodianDuplicateCorruptedEdocCount { get; set; }
        public long CustodianDuplicateCorruptedEmbeddedEdocCount { get; set; }
        public long CustodianDuplicateUnknownEmailCount { get; set; }
        public long CustodianDuplicateUnknownAttachmentCount { get; set; }
        public long CustodianDuplicateUnknownEdocCount { get; set; }
        public long CustodianDuplicateUnknownEmbeddedEdocCount { get; set; }
        public long CustodianDuplicateProcessingErrorEmailCount { get; set; }
        public long CustodianDuplicateProcessingErrorAttachmentCount { get; set; }
        public long CustodianDuplicateProcessingErrorEdocCount { get; set; }
        public long CustodianDuplicateProcessingErrorEmbeddedEdocCount { get; set; }
        public long OriginalZeroByteEmailCount { get; set; }
        public long OriginalZeroByteAttachmentCount { get; set; }
        public long OriginalZeroByteEdocCount { get; set; }
        public long OriginalZeroByteEmbeddedCount { get; set; }
        public long DuplicateZeroByteEmailCount { get; set; }
        public long DuplicateZeroByteAttachmentCount { get; set; }
        public long DuplicateZeroByteEdocCount { get; set; }
        public long DuplicateZeroByteEmbeddedCount { get; set; }
        public long CustodianDuplicateZeroByteEmailCount { get; set; }
        public long CustodianDuplicateZeroByteAttachmentCount { get; set; }
        public long CustodianDuplicateZeroByteEdocCount { get; set; }
        public long CustodianDuplicateZeroByteEmbeddedCount { get; set; }
        public long OriginalUnSupportedEmailCount { get; set; }
        public long OriginalUnSupportedAttachmentCount { get; set; }
        public long OriginalUnSupportedEdocCount { get; set; }
        public long OriginalUnSupportedEmbeddedCount { get; set; }
        public long DuplicateUnSupportedEmailCount { get; set; }
        public long DuplicateUnSupportedAttachmentCount { get; set; }
        public long DuplicateUnSupportedEdocCount { get; set; }
        public long DuplicateUnSupportedEmbeddedCount { get; set; }
        public long CustodianDuplicateUnSupportedEmailCount { get; set; }
        public long CustodianDuplicateUnSupportedAttachmentCount { get; set; }
        public long CustodianDuplicateUnSupportedEdocCount { get; set; }
        public long CustodianDuplicateUnSupportedEmbeddedCount { get; set; }
        public long ProcessedDocumentSize { get; set; }
    }
}
