//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lg_ProjectAuditHistory
    {
        public long LogId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public string ItemName { get; set; }
        public string ActionModule { get; set; }
        public string ItemIdIdentifier { get; set; }
        public string ActionInfo { get; set; }
        public string OldValue { get; set; }
        public string CurrentValue { get; set; }
        public string DisplayLog { get; set; }
        public Nullable<long> ActionLoggedBy { get; set; }
        public Nullable<System.DateTime> ActionLoggedOn { get; set; }
        public string Application { get; set; }
    }
}
