//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_JB_ScanSource
    {
        public long ID { get; set; }
        public long JobId { get; set; }
        public long MediaSourceAssociationId { get; set; }
        public long MediaId { get; set; }
        public Nullable<int> Status { get; set; }
        public string ProcessingInstanceId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public int RetryCount { get; set; }
    }
}
