//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_emailaddresslist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ex_emailaddresslist()
        {
            this.tbl_ex_GroupEmailList = new HashSet<tbl_ex_GroupEmailList>();
        }
    
        public long EmailAddressID { get; set; }
        public string EmailAddress { get; set; }
        public string EmailName { get; set; }
        public string DomainName { get; set; }
        public bool IsGroup { get; set; }
        public Nullable<decimal> TotalScore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ex_GroupEmailList> tbl_ex_GroupEmailList { get; set; }
    }
}
