//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vod_ExportDownLoadedLog
    {
        public long ExportID { get; set; }
        public int DownloadedBy { get; set; }
        public System.DateTime DownloadedDate { get; set; }
    }
}
