//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_st_StateErrorInfo
    {
        public long Id { get; set; }
        public Nullable<long> JobId { get; set; }
        public bool IsResolved { get; set; }
        public string ResolveType { get; set; }
        public Nullable<long> ResolvingUserId { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public Nullable<bool> IsStateErrorIgnored { get; set; }
    }
}
