//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_var_QCPredictionResult
    {
        public int ProfileID { get; set; }
        public string PredictionID { get; set; }
        public int ReviewsetID { get; set; }
        public long FileID { get; set; }
        public Nullable<int> PredictedCategoryID { get; set; }
        public Nullable<int> QCCategoryID { get; set; }
        public Nullable<bool> IsOverturned { get; set; }
    }
}
