//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_IndexStatusLog
    {
        public long IndexFailureLogId { get; set; }
        public long CustodianId { get; set; }
        public long MediaId { get; set; }
        public long FileId { get; set; }
        public bool IndexedStatus { get; set; }
        public long JobId { get; set; }
        public int Status { get; set; }
        public string ProcessingInstanceId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> ReTryCount { get; set; }
        public bool IsMergedToMainIndex { get; set; }
        public string FullTextType { get; set; }
    
        public virtual tbl_ds_ProjectJobInfo tbl_ds_ProjectJobInfo { get; set; }
        public virtual tbl_ex_FileInfo tbl_ex_FileInfo { get; set; }
    }
}
