//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tg_TagGroupAssociation
    {
        public long TagGroupAssociationID { get; set; }
        public long TagId { get; set; }
        public long TagGroupID { get; set; }
    
        public virtual tbl_ex_tag tbl_ex_tag { get; set; }
        public virtual Tbl_tg_TagGroup Tbl_tg_TagGroup { get; set; }
    }
}
