//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ig_InvalidDate
    {
        public long InvalidDateId { get; set; }
        public long FileId { get; set; }
        public string InvalidDateTime { get; set; }
        public string InvalidDateTimeType { get; set; }
        public string Remark { get; set; }
    
        public virtual tbl_ex_FileInfo tbl_ex_FileInfo { get; set; }
    }
}
