//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_tg_TagGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_tg_TagGroup()
        {
            this.tbl_rev_TagGroupSortOrder = new HashSet<tbl_rev_TagGroupSortOrder>();
            this.tbl_tg_TagGroupAssociation = new HashSet<tbl_tg_TagGroupAssociation>();
            this.tbl_VAR_ProfileInfo = new HashSet<tbl_VAR_ProfileInfo>();
        }
    
        public long TagGroupId { get; set; }
        public string TagGroupName { get; set; }
        public bool IsExclusive { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rev_TagGroupSortOrder> tbl_rev_TagGroupSortOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tg_TagGroupAssociation> tbl_tg_TagGroupAssociation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VAR_ProfileInfo> tbl_VAR_ProfileInfo { get; set; }
    }
}
