//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ex_TagActionLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Ex_TagActionLog()
        {
            this.tbl_ex_TagHistory = new HashSet<tbl_ex_TagHistory>();
        }
    
        public long BatchID { get; set; }
        public byte TagOrUntagType { get; set; }
        public string TagedOrUntaggedFromModule { get; set; }
        public bool IsTagOperation { get; set; }
        public string TaggedOrUntaggedObject { get; set; }
        public string TaggedOrUntaggedObjectValue { get; set; }
        public bool ApplyDateFilter { get; set; }
        public Nullable<long> SearchID { get; set; }
        public Nullable<System.DateTime> DateFilterStartDateTime { get; set; }
        public Nullable<System.DateTime> DateFilterEndDateTime { get; set; }
        public string MediaList { get; set; }
        public long TagID { get; set; }
        public System.DateTime TagAppliedDate { get; set; }
        public long TagOrUntaggedBy { get; set; }
        public Nullable<long> TotalTaggedOrUntaggedCount { get; set; }
        public Nullable<long> TotalDuplicateCount { get; set; }
        public Nullable<long> ParentFileCount { get; set; }
        public string Comment { get; set; }
        public bool PCPropagationOption { get; set; }
        public int DuplicatePropagationOption { get; set; }
        public Nullable<long> ReviewBatchID { get; set; }
        public Nullable<bool> EmailThreadPropagationOption { get; set; }
        public Nullable<bool> ShowIndirectHitsInSearch { get; set; }
        public Nullable<long> PCSetPropagationCount { get; set; }
        public Nullable<long> DupeOptionFromSearch { get; set; }
        public Nullable<long> SelectedCount { get; set; }
        public Nullable<long> EmailThreadCount { get; set; }
        public string NavigatedBy { get; set; }
        public string NavigationList { get; set; }
        public int NddPropagationOption { get; set; }
        public Nullable<long> NddPropagationCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ex_TagHistory> tbl_ex_TagHistory { get; set; }
    }
}
