//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ft_FullTextMaster
    {
        public long FileId { get; set; }
        public string DefaultPreference { get; set; }
        public string ExportPreference { get; set; }
        public Nullable<bool> IsSetByUser { get; set; }
    }
}
