//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ex_searchlog
    {
        public long SearchID { get; set; }
        public string NavigationList { get; set; }
        public string searchexpression { get; set; }
        public bool IncludeParentChild { get; set; }
        public string SearchQuery { get; set; }
        public long TotalHitCount { get; set; }
        public Nullable<System.DateTime> SearchEndDateTime { get; set; }
        public string SearchName { get; set; }
        public Nullable<int> SearchedBy { get; set; }
        public bool isfileidsearch { get; set; }
        public bool isentryidsearch { get; set; }
        public byte[] LoadFile { get; set; }
        public string SearchFileType { get; set; }
        public Nullable<bool> IsLoadFileSearch { get; set; }
        public bool IsSqlMode { get; set; }
        public bool SaveSearch { get; set; }
        public int SearchDuplicateOption { get; set; }
        public string TagsInSearch { get; set; }
        public System.DateTime SearchStartDateTime { get; set; }
        public bool SearchComplete { get; set; }
        public string NavigationBy { get; set; }
        public Nullable<bool> HasUnindexedMedias { get; set; }
        public Nullable<bool> IsCombinedSearch { get; set; }
        public string Remarks { get; set; }
        public bool IsAutoSearch { get; set; }
        public Nullable<long> CustomFieldId { get; set; }
        public Nullable<long> TagGroupId { get; set; }
    }
}
