//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ps_ScanFileInfo
    {
        public long ScanFileId { get; set; }
        public long CustodianId { get; set; }
        public long MediaId { get; set; }
        public string FileExt { get; set; }
        public long FileSize { get; set; }
        public string FileFullPath { get; set; }
        public long MediaSourceAssociationId { get; set; }
        public string UniqueIdentifier { get; set; }
        public string AdditionalFileInfoValues { get; set; }
    }
}
