//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_prt_PrintTiffSettings
    {
        public long PrintId { get; set; }
        public string PrintName { get; set; }
        public long CreatedBy { get; set; }
        public string PrintOptions { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string FileLocation { get; set; }
    }
}
