//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jb_Import
    {
        public long JobId { get; set; }
        public long UploadId { get; set; }
        public int Status { get; set; }
        public string ProcessingInstanceId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public int ReTryCount { get; set; }
        public int Phase { get; set; }
        public bool AutoAnalyzeUpload { get; set; }
        public bool AutoValidateFields { get; set; }
        public long ImportId { get; set; }
    }
}
