//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tiff_Shadow
    {
        public long fileId { get; set; }
        public string uncfile { get; set; }
        public Nullable<int> Processingflag { get; set; }
        public string processingID { get; set; }
        public Nullable<int> ErrorType { get; set; }
        public Nullable<long> CustodianId { get; set; }
        public Nullable<long> MediaId { get; set; }
        public Nullable<long> BatchId { get; set; }
        public Nullable<int> TotalPageCount { get; set; }
        public Nullable<int> TagType { get; set; }
        public Nullable<bool> Hardlimit { get; set; }
        public Nullable<int> PageLimit { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string TiffSource { get; set; }
        public long RetryCount { get; set; }
        public string BatesPrefix { get; set; }
        public Nullable<int> BatesPadding { get; set; }
        public Nullable<long> BatesStartNumber { get; set; }
        public string TiffImagingEngine { get; set; }
        public string ErrorDescription { get; set; }
        public string TiffImagingEngineToUse { get; set; }
        public string ColorConversionSetting { get; set; }
        public string CutoffOption { get; set; }
    }
}
