//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VAR_TF_shadow
    {
        public string TrainingItemID { get; set; }
        public Nullable<long> FileId { get; set; }
        public Nullable<int> ProcessingFlag { get; set; }
        public string ProcessingID { get; set; }
        public Nullable<int> ErrorType { get; set; }
        public Nullable<long> JobID { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public long RetryCount { get; set; }
        public string FulltextType { get; set; }
    
        public virtual tbl_ds_ProjectJobInfo tbl_ds_ProjectJobInfo { get; set; }
        public virtual tbl_VAR_RejectedTrainingItems tbl_VAR_RejectedTrainingItems { get; set; }
    }
}
