//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lg_ImportLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_lg_ImportLog()
        {
            this.tbl_rev_FileInfo = new HashSet<tbl_rev_FileInfo>();
        }
    
        public long ImportLogId { get; set; }
        public long ReviewSetId { get; set; }
        public int ImportedBy { get; set; }
        public System.DateTime ImportedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rev_FileInfo> tbl_rev_FileInfo { get; set; }
    }
}
