//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fld_GroupFieldAssociation
    {
        public long FieldID { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public bool IsCustomField { get; set; }
    
        public virtual tbl_pj_GroupInfo tbl_pj_GroupInfo { get; set; }
    }
}
