//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ig_FileTypeTimeoutLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ig_FileTypeTimeoutLog()
        {
            this.tbl_ig_TimeOutByFiletype = new HashSet<tbl_ig_TimeOutByFiletype>();
            this.tbl_ig_TimeoutJobAssociation = new HashSet<tbl_ig_TimeoutJobAssociation>();
        }
    
        public long TimeOutLogId { get; set; }
        public long UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Module { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ig_TimeOutByFiletype> tbl_ig_TimeOutByFiletype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ig_TimeoutJobAssociation> tbl_ig_TimeoutJobAssociation { get; set; }
    }
}
