//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tg_TagRuleDetail
    {
        public long TagRuleDetailId { get; set; }
        public long TagRuleId { get; set; }
        public long TagId { get; set; }
        public bool IsBaseTag { get; set; }
    
        public virtual tbl_tg_TagRuleInfo tbl_tg_TagRuleInfo { get; set; }
    }
}
