//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lg_DocumentViewerLog
    {
        public long LogId { get; set; }
        public Nullable<int> UserId { get; set; }
        public long FileId { get; set; }
        public System.DateTime ViewedDate { get; set; }
        public string ViewedFrom { get; set; }
        public Nullable<int> ExternalUserId { get; set; }
    }
}
