//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rev_ReviewBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_rev_ReviewBatch()
        {
            this.tbl_rev_BatchFileAssociation = new HashSet<tbl_rev_BatchFileAssociation>();
        }
    
        public long BatchId { get; set; }
        public long ReviewSetId { get; set; }
        public string BatchName { get; set; }
        public int BatchStatus { get; set; }
        public Nullable<int> BatchRequestedBy { get; set; }
        public Nullable<System.DateTime> CheckedOutOn { get; set; }
        public Nullable<System.DateTime> CommitedOn { get; set; }
        public Nullable<long> OriginalPartialCommitBatchId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rev_BatchFileAssociation> tbl_rev_BatchFileAssociation { get; set; }
        public virtual tbl_rev_ReviewSetInfo tbl_rev_ReviewSetInfo { get; set; }
    }
}
