//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ft_ImageFullText
    {
        public long FileID { get; set; }
        public int PageNumber { get; set; }
        public string TiffOCRFulltextFileLocation { get; set; }
        public Nullable<bool> TiffOCRErrored { get; set; }
        public Nullable<int> TiffOCRErrorType { get; set; }
        public string RedactedOCRFulltextFileLocation { get; set; }
        public Nullable<System.DateTime> RedactedOCRRedactedDate { get; set; }
        public Nullable<bool> RedactedOCRErrored { get; set; }
        public Nullable<int> RedactedOCRErrorType { get; set; }
        public string PrinterTextFullTextFileLocation { get; set; }
        public Nullable<long> GeneratedTiffOCRFulltextSize { get; set; }
        public Nullable<long> RedactedTiffOCRFulltextSize { get; set; }
        public Nullable<System.DateTime> GeneratedOCRDate { get; set; }
        public string RedactionSet { get; set; }
    }
}
