//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rev_TagGroupSortOrder
    {
        public long ReviewSetId { get; set; }
        public long TagGroupId { get; set; }
        public Nullable<long> SortOrder { get; set; }
    
        public virtual tbl_rev_ReviewSetInfo tbl_rev_ReviewSetInfo { get; set; }
        public virtual Tbl_tg_TagGroup Tbl_tg_TagGroup { get; set; }
    }
}
